const q = (id, question, options, answer, explanation) => ({
  id,
  question,
  options,
  answer,
  explanation,
})

const QUIZ_SELECTION_COUNT = 20

export const QUIZ_BANK = {
  Perceptron: [
    q(1, 'What is a perceptron?', ['Loss function', 'Neural network unit', 'Optimizer', 'Dataset'], 'Neural network unit', 'A perceptron is the fundamental computational unit used in neural networks.'),
    q(2, 'A single-layer perceptron can solve:', ['Non-linear problems', 'Linear problems', 'Sequential problems', 'Image problems'], 'Linear problems', 'A single-layer perceptron models linearly separable decision boundaries.'),
    q(3, 'What does a perceptron compute first?', ['Loss', 'Weighted sum', 'Gradient', 'Accuracy'], 'Weighted sum', 'It first computes a weighted sum of inputs and bias.'),
    q(4, 'What is the role of weights?', ['Normalize data', 'Assign importance to inputs', 'Store output', 'Calculate loss'], 'Assign importance to inputs', 'Weights control how much each input contributes to the output.'),
    q(5, 'What is bias used for?', ['Increase loss', 'Shift decision boundary', 'Normalize data', 'Reduce inputs'], 'Shift decision boundary', 'Bias shifts the decision boundary to improve flexibility.'),
    q(6, 'Activation function is used to:', ['Store weights', 'Add non-linearity', 'Normalize data', 'Remove bias'], 'Add non-linearity', 'Activation functions add non-linearity to neural models.'),
    q(7, 'Which activation is common for binary output?', ['ReLU', 'Sigmoid', 'Softmax', 'Tanh'], 'Sigmoid', 'Sigmoid maps outputs to a probability-like range (0, 1).'),
    q(8, 'Decision boundary of single-layer perceptron is:', ['Curve', 'Line', 'Circle', 'Random'], 'Line', 'A single-layer perceptron creates a linear boundary.'),
    q(9, 'Multilayer perceptron (MLP) includes:', ['Only input layer', 'Hidden layers', 'Only output layer', 'No layers'], 'Hidden layers', 'MLPs include one or more hidden layers between input and output.'),
    q(10, 'MLP can solve:', ['Only linear problems', 'Non-linear problems', 'Only binary problems', 'Only regression'], 'Non-linear problems', 'Hidden layers and activations enable non-linear learning.'),
    q(11, 'XOR problem requires:', ['Single layer', 'Multilayer perceptron', 'No network', 'Linear model'], 'Multilayer perceptron', 'XOR is non-linearly separable and needs hidden layers.'),
    q(12, 'Why does XOR fail in single-layer perceptron?', ['Too many inputs', 'Non-linear separability', 'Low data', 'High bias'], 'Non-linear separability', 'Single-layer perceptrons cannot solve non-linearly separable patterns.'),
    q(13, 'Input × Weight results in:', ['Gradient', 'Weighted input', 'Loss', 'Output'], 'Weighted input', 'Each input is scaled by its corresponding weight.'),
    q(14, 'Output of perceptron depends on:', ['Only input', 'Only weights', 'Input + weights + bias', 'Dataset'], 'Input + weights + bias', 'Perceptron output is determined by inputs, weights, and bias.'),
    q(15, 'More layers allow:', ['Faster training only', 'Better visualization', 'Learning complex patterns', 'Less computation'], 'Learning complex patterns', 'Deeper networks learn more complex feature relationships.'),
    q(16, 'What happens without activation function?', ['Better learning', 'Linear model', 'Non-linear model', 'Faster convergence'], 'Linear model', 'Without activation, stacked layers collapse into a linear transformation.'),
    q(17, 'Hidden layers perform:', ['Data storage', 'Feature transformation', 'Output generation', 'Loss calculation'], 'Feature transformation', 'Hidden layers transform raw inputs into useful internal representations.'),
    q(18, 'Perceptron is used for:', ['Sorting', 'Classification', 'Searching', 'Clustering'], 'Classification', 'Perceptrons are core classifiers in neural network models.'),
    q(19, 'Linear separability means:', ['Data can be clustered', 'Data separated by line', 'Data sorted', 'Data normalized'], 'Data separated by line', 'Linearly separable data can be split by a straight boundary.'),
    q(20, 'If data is not linearly separable, use:', ['Single layer', 'MLP', 'Logistic regression', 'None'], 'MLP', 'An MLP can model non-linear boundaries using hidden layers.'),
    q(21, 'MLP uses which structure?', ['Sequential layers', 'Parallel layers', 'No layers', 'Circular layers'], 'Sequential layers', 'MLPs are built as sequential feed-forward layers.'),
    q(22, 'Output layer typically uses:', ['ReLU', 'Sigmoid', 'Dropout', 'Pooling'], 'Sigmoid', 'For binary outputs, sigmoid is a standard output activation.'),
    q(23, 'Weights are updated during:', ['Testing', 'Training', 'Prediction', 'Evaluation'], 'Training', 'Parameter updates happen during training via optimization.'),
    q(24, 'Bias helps in:', ['Reducing loss', 'Flexibility of boundary', 'Increasing data', 'Sorting inputs'], 'Flexibility of boundary', 'Bias gives the model flexibility by shifting the boundary.'),
    q(25, 'Too many layers may cause:', ['Underfitting', 'Overfitting', 'Normalization', 'Clustering'], 'Overfitting', 'Very deep models may overfit if not regularized properly.'),
    q(26, 'Which layer receives raw input?', ['Hidden', 'Output', 'Input layer', 'Activation'], 'Input layer', 'Raw features are fed into the input layer.'),
    q(27, 'Which layer produces final output?', ['Input', 'Hidden', 'Output layer', 'Activation'], 'Output layer', 'Predictions are produced by the output layer.'),
    q(28, 'Perceptron is inspired by:', ['CPU', 'Human neuron', 'GPU', 'Database'], 'Human neuron', 'Perceptron design is inspired by biological neurons.'),
    q(29, 'MLP stands for:', ['Multi Linear Processor', 'Multi Layer Perceptron', 'Machine Learning Process', 'Model Learning Path'], 'Multi Layer Perceptron', 'MLP is short for Multi Layer Perceptron.'),
    q(30, 'Activation function introduces:', ['Noise', 'Non-linearity', 'Error', 'Bias'], 'Non-linearity', 'Non-linearity is necessary to model complex patterns.'),
    q(31, 'Which is NOT part of perceptron?', ['Weights', 'Bias', 'Activation', 'Pooling'], 'Pooling', 'Pooling is typically used in CNNs, not standard perceptrons.'),
    q(32, 'Input features are also called:', ['Outputs', 'Variables', 'Labels', 'Loss'], 'Variables', 'Input features are variables used by the model.'),
    q(33, 'Perceptron output is:', ['Always 0', 'Always 1', 'Depends on input', 'Random'], 'Depends on input', 'Predictions depend on both inputs and learned parameters.'),
    q(34, 'Training improves:', ['Speed', 'Accuracy', 'Size', 'Memory'], 'Accuracy', 'Training aims to improve predictive performance.'),
    q(35, 'Which problem needs MLP?', ['XOR', 'Linear', 'Simple classification', 'Sorting'], 'XOR', 'XOR requires non-linear representation from hidden layers.'),
    q(36, 'Too few layers cause:', ['Overfitting', 'Underfitting', 'Explosion', 'Noise'], 'Underfitting', 'Insufficient model capacity often leads to underfitting.'),
    q(37, 'Weights are initialized:', ['Always zero', 'Randomly', 'Fixed', 'None'], 'Randomly', 'Random initialization helps break symmetry during training.'),
    q(38, 'Perceptron works best for:', ['Sequential data', 'Linear data', 'Image data', 'Audio'], 'Linear data', 'Single-layer perceptrons are best for linearly separable data.'),
    q(39, 'Feature scaling helps:', ['Speed training', 'Reduce loss', 'Both', 'None'], 'Both', 'Scaling can improve convergence speed and optimization quality.'),
    q(40, 'Input layer has:', ['Weights', 'Data', 'Loss', 'Gradients'], 'Data', 'The input layer receives feature data.'),
    q(41, 'Output depends on:', ['Training', 'Input', 'Model parameters', 'All'], 'All', 'Output depends on data, parameters, and learned training state.'),
    q(42, 'Decision boundary is:', ['Output', 'Separator', 'Input', 'Loss'], 'Separator', 'It separates classes in feature space.'),
    q(43, 'MLP uses:', ['One layer', 'Multiple layers', 'No layer', 'Two layers only'], 'Multiple layers', 'MLPs use multiple feed-forward layers.'),
    q(44, 'Which is linear model?', ['CNN', 'RNN', 'Single-layer perceptron', 'Transformer'], 'Single-layer perceptron', 'A single-layer perceptron is linear in its decision function.'),
    q(45, 'Which is non-linear model?', ['Single-layer', 'MLP', 'Linear regression', 'PCA'], 'MLP', 'MLPs become non-linear through hidden layers and activations.'),
    q(46, 'Sigmoid output range is:', ['(-1,1)', '(0,1)', '(0,∞)', '(-∞,∞)'], '(0,1)', 'Sigmoid maps any real input to (0,1).'),
    q(47, 'ReLU output is:', ['Negative only', 'Positive only', 'max(0,x)', 'x²'], 'max(0,x)', 'ReLU outputs zero for negative inputs and x for positive inputs.'),
    q(48, 'Hidden layers help in:', ['Visualization', 'Feature extraction', 'Storage', 'Input'], 'Feature extraction', 'Hidden layers extract and transform informative features.'),
    q(49, 'Training adjusts:', ['Inputs', 'Outputs', 'Weights', 'Labels'], 'Weights', 'Learning changes model parameters, mainly weights and bias.'),
    q(50, 'Perceptron is building block of:', ['Database', 'Neural networks', 'Sorting', 'Search'], 'Neural networks', 'Perceptrons are core building blocks of neural network architectures.'),
  ],
  'Neural Flow Engine': [
    q(1, 'What is the neural learning cycle?', ['Data preprocessing method', 'Model training loop', 'Visualization technique', 'Optimization algorithm'], 'Model training loop', 'The neural learning cycle is the repeated training loop used to improve model parameters.'),
    q(2, 'Which is the correct order of stages?', ['Loss -> Forward -> Update -> Backprop', 'Forward -> Loss -> Backprop -> Update', 'Backprop -> Forward -> Loss -> Update', 'Update -> Forward -> Loss -> Backprop'], 'Forward -> Loss -> Backprop -> Update', 'A standard training step predicts first, computes loss, backpropagates gradients, then updates weights.'),
    q(3, 'Forward pass is used to:', ['Update weights', 'Compute gradients', 'Generate predictions', 'Normalize data'], 'Generate predictions', 'The forward pass computes outputs from inputs using current parameters.'),
    q(4, 'Loss represents:', ['Accuracy', 'Error between prediction and actual', 'Input value', 'Output layer'], 'Error between prediction and actual', 'Loss quantifies prediction error.'),
    q(5, 'Backpropagation computes:', ['Outputs', 'Gradients', 'Inputs', 'Labels'], 'Gradients', 'Backpropagation computes derivatives used for optimization.'),
    q(6, 'Weight update is done using:', ['Loss', 'Gradient', 'Input', 'Output'], 'Gradient', 'Gradients guide parameter updates.'),
    q(7, 'Learning rate controls:', ['Input size', 'Step size of updates', 'Output value', 'Data size'], 'Step size of updates', 'Learning rate sets how large each parameter update is.'),
    q(8, 'What repeats in training?', ['Forward only', 'Backprop only', 'Entire cycle', 'Loss only'], 'Entire cycle', 'Training repeats all core stages together.'),
    q(9, 'One complete cycle is called:', ['Batch', 'Epoch', 'Iteration', 'Layer'], 'Iteration', 'One forward-loss-backprop-update step is an iteration.'),
    q(10, 'Multiple iterations form:', ['Dataset', 'Epoch', 'Gradient', 'Feature'], 'Epoch', 'An epoch is one full pass over the training dataset.'),
    q(11, 'Forward pass flows:', ['Right to left', 'Left to right', 'Random', 'Circular'], 'Left to right', 'Computation moves from input toward output.'),
    q(12, 'Backpropagation flows:', ['Left to right', 'Right to left', 'Random', 'Circular'], 'Right to left', 'Gradient flow moves from output layer back toward earlier layers.'),
    q(13, 'Loss is computed after:', ['Backprop', 'Update', 'Forward pass', 'Input'], 'Forward pass', 'You need predictions first before computing loss.'),
    q(14, 'Gradients indicate:', ['Output', 'Direction of change', 'Input size', 'Loss value'], 'Direction of change', 'Gradients indicate how to change weights to reduce loss.'),
    q(15, 'Weight update reduces:', ['Input', 'Loss', 'Data', 'Features'], 'Loss', 'Parameter updates aim to minimize the loss function.'),
    q(16, 'Why do we compute loss?', ['To increase error', 'To measure error', 'To store data', 'To normalize input'], 'To measure error', 'Loss is the training signal that measures performance.'),
    q(17, 'If loss is high, model is:', ['Accurate', 'Wrong', 'Perfect', 'Stable'], 'Wrong', 'High loss means predictions are far from targets.'),
    q(18, 'Backpropagation uses:', ['Matrix multiplication', 'Chain rule', 'Sorting', 'Clustering'], 'Chain rule', 'Backprop relies on the chain rule to propagate gradients.'),
    q(19, 'Gradient tells:', ['Output', 'Direction to reduce loss', 'Input', 'Data size'], 'Direction to reduce loss', 'Gradient direction is used for optimization updates.'),
    q(20, 'What happens if learning rate is too high?', ['Slow learning', 'Stable learning', 'Unstable training', 'No change'], 'Unstable training', 'Very large updates can overshoot minima and destabilize training.'),
    q(21, 'If learning rate is too low?', ['Fast learning', 'Slow learning', 'Overfitting', 'Explosion'], 'Slow learning', 'Very small updates make convergence slow.'),
    q(22, 'Loss decreasing means:', ['Model worsening', 'Model improving', 'Model stuck', 'Data incorrect'], 'Model improving', 'A falling loss usually indicates better fit to training data.'),
    q(23, 'Flat loss curve indicates:', ['Learning', 'No learning', 'Overfitting', 'Underflow'], 'No learning', 'A flat curve can indicate stalled optimization.'),
    q(24, 'Increasing loss indicates:', ['Good training', 'Poor training', 'Stable model', 'Balanced model'], 'Poor training', 'Rising loss is typically a sign of training issues.'),
    q(25, 'Backpropagation needs:', ['Loss', 'Input', 'Output', 'Data'], 'Loss', 'Loss provides the scalar objective to differentiate.'),
    q(26, 'Weight update happens:', ['Before forward', 'After backprop', 'Before loss', 'Before input'], 'After backprop', 'Updates are applied once gradients are computed.'),
    q(27, 'What is gradient descent?', ['Loss calculation', 'Weight update method', 'Input processing', 'Data normalization'], 'Weight update method', 'Gradient descent updates parameters opposite the gradient direction.'),
    q(28, 'Forward pass uses:', ['Gradients', 'Weights', 'Loss', 'Labels'], 'Weights', 'Predictions are produced from current model weights.'),
    q(29, 'Backpropagation updates:', ['Output', 'Weights indirectly', 'Inputs', 'Labels'], 'Weights indirectly', 'Backprop computes gradients that are then used to update weights.'),
    q(30, 'Training goal is to:', ['Increase loss', 'Minimize loss', 'Maximize data', 'Normalize input'], 'Minimize loss', 'Training optimizes parameters to reduce the objective.'),
    q(31, 'If prediction = 0.9 and actual = 1, loss is:', ['High', 'Low', 'Zero', 'Infinite'], 'Low', 'Prediction is close to target, so error is typically low.'),
    q(32, 'If prediction = 0.1 and actual = 1:', ['Low error', 'High error', 'No error', 'Stable'], 'High error', 'Prediction is far from target, so loss is high.'),
    q(33, 'Gradient is zero means:', ['Maximum learning', 'No learning', 'High loss', 'Data error'], 'No learning', 'Zero gradient implies no immediate update signal.'),
    q(34, 'If loss oscillates:', ['Stable learning', 'Unstable learning', 'Perfect model', 'No change'], 'Unstable learning', 'Oscillation often means updates are too aggressive or optimization is unstable.'),
    q(35, 'Small gradients cause:', ['Fast learning', 'Slow learning', 'Overfitting', 'Explosion'], 'Slow learning', 'Tiny gradients lead to small parameter updates.'),
    q(36, 'Large gradients cause:', ['Slow learning', 'Instability', 'Accuracy', 'Stability'], 'Instability', 'Very large gradients can produce unstable jumps.'),
    q(37, 'If model improves slowly:', ['Increase learning rate', 'Decrease learning rate', 'Stop training', 'Remove loss'], 'Increase learning rate', 'A larger step size can speed progress if training remains stable.'),
    q(38, 'If model unstable:', ['Increase learning rate', 'Reduce learning rate', 'Add data', 'Remove weights'], 'Reduce learning rate', 'Lowering learning rate often stabilizes training.'),
    q(39, 'Epoch means:', ['One data point', 'One full dataset pass', 'One layer', 'One weight'], 'One full dataset pass', 'An epoch covers all training samples once.'),
    q(40, 'Iteration means:', ['One cycle', 'One dataset', 'One model', 'One layer'], 'One cycle', 'An iteration is one training step/cycle.'),
    q(41, 'Why repeat training cycles?', ['Increase data', 'Improve learning', 'Store outputs', 'Reduce features'], 'Improve learning', 'Repeated updates gradually improve model parameters.'),
    q(42, 'Forward pass uses:', ['Old weights', 'New weights', 'Random weights', 'No weights'], 'Old weights', 'Each forward pass uses the current weights before the next update.'),
    q(43, 'Backprop uses:', ['Future data', 'Past forward values', 'Random data', 'Labels only'], 'Past forward values', 'Backprop differentiates through values computed in the forward pass.'),
    q(44, 'Weight update uses:', ['Loss directly', 'Gradient', 'Input', 'Output'], 'Gradient', 'Updates are based on gradient information.'),
    q(45, 'If gradients wrong, then:', ['Good learning', 'Wrong learning', 'No learning', 'Stable'], 'Wrong learning', 'Incorrect gradients push parameters in the wrong direction.'),
    q(46, 'Learning cycle depends on:', ['Data', 'Model', 'Hyperparameters', 'All'], 'All', 'Training behavior depends on data quality, architecture, and hyperparameters.'),
    q(47, 'Loss function defines:', ['Model size', 'Error measure', 'Input', 'Output'], 'Error measure', 'The loss function specifies how prediction error is measured.'),
    q(48, 'Chain rule is used in:', ['Forward pass', 'Backpropagation', 'Loss', 'Update'], 'Backpropagation', 'Backpropagation uses chain rule across layers.'),
    q(49, 'Training ends when:', ['Loss minimized', 'Epoch complete', 'Data finished', 'Random'], 'Loss minimized', 'A common stopping target is minimizing loss to an acceptable level.'),
    q(50, 'Neural learning cycle ensures:', ['Data storage', 'Model learning', 'Feature removal', 'Output generation'], 'Model learning', 'The cycle iteratively improves the model through feedback and updates.'),
  ],
  'CNN Lab': [
    q(1, 'What is the main purpose of CNN?', ['Process text', 'Process sequential data', 'Process image/spatial data', 'Store data'], 'Process image/spatial data', 'CNNs are built primarily for spatially structured inputs like images.'),
    q(2, 'CNN stands for:', ['Convolution Neural Network', 'Convolutional Neural Network', 'Connected Neural Network', 'Central Neural Network'], 'Convolutional Neural Network', 'CNN is the abbreviation of Convolutional Neural Network.'),
    q(3, 'CNN is mainly used for:', ['Sorting', 'Searching', 'Image processing', 'Clustering'], 'Image processing', 'CNNs excel at image processing and recognition tasks.'),
    q(4, 'CNN detects features like:', ['Numbers', 'Edges and textures', 'Words', 'Dates'], 'Edges and textures', 'Early CNN filters detect low-level patterns like edges and textures.'),
    q(5, 'A filter in CNN is:', ['Dataset', 'Small matrix', 'Output', 'Loss'], 'Small matrix', 'Filters are small kernels convolved over input data.'),
    q(6, 'Convolution operation does:', ['Add noise', 'Extract features', 'Reduce data', 'Normalize'], 'Extract features', 'Convolution extracts local feature responses.'),
    q(7, 'Output of convolution is called:', ['Gradient', 'Feature map', 'Loss', 'Weight'], 'Feature map', 'Each filter produces one feature map.'),
    q(8, 'Pooling layer is used to:', ['Increase size', 'Reduce dimensions', 'Add features', 'Train model'], 'Reduce dimensions', 'Pooling downsamples feature maps.'),
    q(9, 'Most common pooling type:', ['Average', 'Max pooling', 'Min pooling', 'Sum pooling'], 'Max pooling', 'Max pooling is widely used to keep strongest activations.'),
    q(10, 'ReLU is used to:', ['Normalize data', 'Add non-linearity', 'Reduce loss', 'Remove features'], 'Add non-linearity', 'ReLU introduces non-linear behavior needed for deep learning.'),
    q(11, 'CNN reduces parameters using:', ['Full connections', 'Local connections', 'Random weights', 'Bias'], 'Local connections', 'Local receptive fields reduce parameter count compared to dense layers.'),
    q(12, 'Flatten layer is used to:', ['Reduce size', 'Convert to vector', 'Add layers', 'Remove features'], 'Convert to vector', 'Flatten reshapes feature maps into a 1D vector for dense layers.'),
    q(13, 'Final layer in CNN is usually:', ['Pooling', 'Convolution', 'Fully connected', 'Dropout'], 'Fully connected', 'CNN classifiers usually end with one or more dense layers.'),
    q(14, 'Softmax is used for:', ['Regression', 'Classification', 'Sorting', 'Clustering'], 'Classification', 'Softmax converts logits into class probabilities.'),
    q(15, 'CNN works best with:', ['Text data', 'Sequential data', 'Spatial data', 'Audio only'], 'Spatial data', 'CNNs exploit spatial locality and translation patterns.'),
    q(16, 'Why CNN instead of MLP for images?', ['Faster training', 'Fewer parameters', 'Better memory', 'No weights'], 'Fewer parameters', 'Weight sharing and local connections make CNNs parameter efficient.'),
    q(17, 'What does stride control?', ['Input size', 'Filter movement', 'Output', 'Loss'], 'Filter movement', 'Stride determines how far the kernel moves each step.'),
    q(18, 'Padding is used to:', ['Reduce output', 'Maintain size', 'Remove data', 'Normalize input'], 'Maintain size', 'Padding helps preserve spatial dimensions and border info.'),
    q(19, 'Increasing filters results in:', ['Less features', 'More feature detection', 'Less accuracy', 'Smaller model'], 'More feature detection', 'More filters allow learning a richer set of patterns.'),
    q(20, 'Early CNN layers detect:', ['Objects', 'Edges', 'Faces', 'Text'], 'Edges', 'Early layers capture simple local structures.'),
    q(21, 'Deeper CNN layers detect:', ['Edges', 'Pixels', 'Complex objects', 'Noise'], 'Complex objects', 'Deeper layers combine simple features into complex concepts.'),
    q(22, 'Feature maps represent:', ['Input', 'Detected patterns', 'Loss', 'Labels'], 'Detected patterns', 'Feature maps encode where specific patterns appear.'),
    q(23, 'Why pooling is important?', ['Increase data', 'Reduce computation', 'Increase loss', 'Normalize input'], 'Reduce computation', 'Pooling reduces spatial resolution and compute cost.'),
    q(24, 'Too much pooling causes:', ['Overfitting', 'Loss of information', 'Faster training', 'Stability'], 'Loss of information', 'Aggressive downsampling can remove important details.'),
    q(25, 'CNN shares weights to:', ['Increase parameters', 'Reduce parameters', 'Increase loss', 'Store data'], 'Reduce parameters', 'Weight sharing greatly lowers model complexity.'),
    q(26, 'Convolution focuses on:', ['Global features', 'Local features', 'Output', 'Labels'], 'Local features', 'Convolution captures local neighborhood patterns.'),
    q(27, 'Kernel size determines:', ['Output', 'Area of feature detection', 'Loss', 'Data size'], 'Area of feature detection', 'Kernel size sets the receptive field of each operation.'),
    q(28, 'CNN reduces overfitting using:', ['Pooling', 'Dropout', 'Both', 'None'], 'Both', 'Pooling and dropout are both common regularization tools.'),
    q(29, 'Feature hierarchy means:', ['Same features', 'Increasing complexity', 'Decreasing size', 'Random patterns'], 'Increasing complexity', 'Layers build from simple to complex feature representations.'),
    q(30, 'CNN uses which type of connection?', ['Fully connected', 'Local connected', 'Random', 'Sequential'], 'Local connected', 'Convolution layers use local connectivity patterns.'),
    q(31, 'If filter detects edges, output will show:', ['Colors', 'Edge patterns', 'Noise', 'Labels'], 'Edge patterns', 'Feature maps highlight regions matching learned filters.'),
    q(32, 'If image size reduces too much:', ['More accuracy', 'Loss of details', 'Faster training only', 'Better features'], 'Loss of details', 'Excessive downsampling can discard important spatial information.'),
    q(33, 'If too many filters used early:', ['Efficient model', 'Heavy computation', 'Better performance', 'Faster training'], 'Heavy computation', 'Large filter counts increase compute and memory demand.'),
    q(34, 'If no pooling used:', ['Loss decreases', 'High computation', 'Faster model', 'Better accuracy'], 'High computation', 'Without pooling, feature maps stay large and expensive.'),
    q(35, 'If CNN overfits:', ['Reduce layers', 'Add dropout', 'Increase data', 'All'], 'All', 'Multiple strategies can be used together to reduce overfitting.'),
    q(36, 'If dataset small:', ['CNN works best', 'Overfitting risk', 'No issue', 'Faster training'], 'Overfitting risk', 'Small datasets increase risk of memorization.'),
    q(37, 'If stride increases:', ['Output size increases', 'Output size decreases', 'No change', 'Loss increases'], 'Output size decreases', 'Larger strides sample fewer positions, shrinking outputs.'),
    q(38, 'If padding not used:', ['Output shrinks', 'Output increases', 'No change', 'Loss decreases'], 'Output shrinks', 'Valid convolution reduces spatial dimensions.'),
    q(39, 'If kernel size large:', ['More local detail', 'More global view', 'Faster training', 'Less computation'], 'More global view', 'Larger kernels cover wider context each step.'),
    q(40, 'CNN fails when:', ['Image data', 'Sequential data', 'Spatial data', 'Large data'], 'Sequential data', 'CNNs are not naturally ideal for long temporal dependencies.'),
    q(41, 'CNN parameter efficiency comes from:', ['Pooling', 'Weight sharing', 'Activation', 'Bias'], 'Weight sharing', 'Shared kernels reduce number of trainable parameters.'),
    q(42, 'Convolution is mathematically:', ['Addition', 'Multiplication + summation', 'Division', 'Sorting'], 'Multiplication + summation', 'Convolution computes weighted sums of local patches.'),
    q(43, 'Feature maps depth equals:', ['Input size', 'Number of filters', 'Loss', 'Labels'], 'Number of filters', 'Each filter generates one channel in output depth.'),
    q(44, 'Flatten layer connects to:', ['Pooling', 'Fully connected', 'Convolution', 'Input'], 'Fully connected', 'Flatten outputs are passed to dense classifier heads.'),
    q(45, 'CNN architecture typically ends with:', ['Pooling', 'Dense layer', 'Input', 'Filter'], 'Dense layer', 'Classification CNNs usually end in dense output stages.'),
    q(46, 'CNN is inspired by:', ['CPU', 'Human vision', 'Database', 'Sorting'], 'Human vision', 'CNNs are inspired by visual cortex receptive field concepts.'),
    q(47, 'Activation function prevents:', ['Overfitting', 'Linearity', 'Data loss', 'Input error'], 'Linearity', 'Activation functions prevent the network from collapsing to linear mapping.'),
    q(48, 'CNN complexity depends on:', ['Filters', 'Layers', 'Kernel size', 'All'], 'All', 'All these design choices affect computation and capacity.'),
    q(49, 'CNN improves accuracy by:', ['Increasing data', 'Learning features', 'Reducing layers', 'Removing filters'], 'Learning features', 'CNNs learn hierarchical features that improve prediction quality.'),
    q(50, 'CNN is best for:', ['Text', 'Images', 'Numbers', 'Tables'], 'Images', 'CNNs are best suited for image and spatial pattern tasks.'),
  ],
  'RNN Lab': [
    q(1, 'What is the main purpose of RNN?', ['Process images', 'Process sequential data', 'Store data', 'Normalize data'], 'Process sequential data', 'RNNs are designed for sequential and temporal data.'),
    q(2, 'RNN stands for:', ['Random Neural Network', 'Recurrent Neural Network', 'Repeated Neural Network', 'Recursive Neural Network'], 'Recurrent Neural Network', 'RNN expands to Recurrent Neural Network.'),
    q(3, 'RNN is mainly used for:', ['Image classification', 'Sequential data', 'Sorting', 'Clustering'], 'Sequential data', 'RNNs are used for data where order matters.'),
    q(4, 'What makes RNN different from MLP?', ['No weights', 'Memory (hidden state)', 'No activation', 'No layers'], 'Memory (hidden state)', 'RNNs maintain hidden state as memory across time steps.'),
    q(5, 'Hidden state represents:', ['Output', 'Memory', 'Input', 'Loss'], 'Memory', 'The hidden state carries contextual memory.'),
    q(6, 'RNN processes data:', ['All at once', 'Step by step', 'Randomly', 'In parallel'], 'Step by step', 'RNNs process one sequence element at a time.'),
    q(7, 'RNN is best for:', ['Images', 'Text', 'Tables', 'Numbers'], 'Text', 'RNNs are commonly used in language tasks.'),
    q(8, 'Each step in RNN depends on:', ['Future data', 'Previous state', 'Output only', 'Loss'], 'Previous state', 'Each state uses prior hidden state information.'),
    q(9, 'RNN output depends on:', ['Only input', 'Only weights', 'Input + past memory', 'Dataset'], 'Input + past memory', 'RNN outputs are influenced by current input and historical context.'),
    q(10, 'Sequence means:', ['Random data', 'Ordered data', 'Sorted data', 'Clustered data'], 'Ordered data', 'A sequence has meaningful order across elements.'),
    q(11, 'Time step refers to:', ['Layer', 'Sequence position', 'Output', 'Loss'], 'Sequence position', 'A time step is a single position in the sequence.'),
    q(12, 'RNN shares weights across:', ['Layers', 'Time steps', 'Inputs', 'Outputs'], 'Time steps', 'The same recurrent weights are reused at each time step.'),
    q(13, 'RNN is useful for:', ['Image recognition', 'Speech recognition', 'Sorting', 'Clustering'], 'Speech recognition', 'Speech is sequential, so RNNs are suitable.'),
    q(14, 'Input in RNN is:', ['Single value', 'Sequence', 'Random', 'Matrix only'], 'Sequence', 'RNNs are built to consume sequences.'),
    q(15, 'Output can be:', ['One value', 'Sequence', 'Both', 'None'], 'Both', 'RNNs can produce one output or outputs at each step.'),
    q(16, 'Why RNN uses memory?', ['Store data', 'Capture sequence context', 'Reduce loss', 'Normalize data'], 'Capture sequence context', 'Memory helps preserve context across steps.'),
    q(17, 'Hidden state updates using:', ['Current input only', 'Previous state only', 'Both', 'None'], 'Both', 'State update combines current input with previous hidden state.'),
    q(18, 'RNN struggles with:', ['Short sequences', 'Long sequences', 'Small data', 'Images'], 'Long sequences', 'Vanilla RNNs have trouble with long-term dependencies.'),
    q(19, 'Vanishing gradient occurs when:', ['Gradients increase', 'Gradients decrease', 'Data increases', 'Output increases'], 'Gradients decrease', 'Very small gradients hinder learning in earlier steps.'),
    q(20, 'Exploding gradient occurs when:', ['Gradients shrink', 'Gradients grow large', 'Data shrinks', 'Output shrinks'], 'Gradients grow large', 'Very large gradients destabilize training.'),
    q(21, 'Why does RNN forget long-term info?', ['Too many layers', 'Gradient decay', 'Low data', 'High bias'], 'Gradient decay', 'Decaying gradients reduce influence of distant steps.'),
    q(22, 'LSTM improves RNN by:', ['Removing layers', 'Better memory handling', 'Reducing data', 'Removing weights'], 'Better memory handling', 'LSTM gates improve retention of long-range context.'),
    q(23, 'GRU is:', ['CNN type', 'RNN variant', 'Loss function', 'Activation'], 'RNN variant', 'GRU is a gated recurrent architecture.'),
    q(24, 'RNN processes sequences:', ['Independently', 'Sequentially', 'Randomly', 'In parallel'], 'Sequentially', 'Sequence elements are processed in temporal order.'),
    q(25, 'Output at time t depends on:', ['Future', 'Past', 'Both', 'None'], 'Past', 'Current prediction depends on prior context.'),
    q(26, 'RNN cannot parallelize easily because:', ['No weights', 'Sequential dependency', 'No data', 'No layers'], 'Sequential dependency', 'Each step depends on the previous step output/state.'),
    q(27, 'RNN training is slower because:', ['Large data', 'Sequential nature', 'Small model', 'No gradients'], 'Sequential nature', 'Step-by-step computation limits parallel execution.'),
    q(28, 'Hidden state acts as:', ['Output', 'Memory', 'Input', 'Loss'], 'Memory', 'It stores and carries context through the sequence.'),
    q(29, 'Activation used in RNN:', ['ReLU only', 'Tanh / Sigmoid', 'Softmax only', 'None'], 'Tanh / Sigmoid', 'Classic RNN cells commonly use tanh or sigmoid activations.'),
    q(30, 'RNN handles:', ['Static data', 'Dynamic data', 'Random data', 'Sorted data'], 'Dynamic data', 'RNNs handle changing temporal patterns.'),
    q(31, 'Sentence prediction uses:', ['CNN', 'RNN', 'MLP', 'PCA'], 'RNN', 'Sentence modeling is a sequence task.'),
    q(32, 'If sequence is long:', ['RNN works perfectly', 'RNN struggles', 'Faster training', 'No issue'], 'RNN struggles', 'Long dependencies are difficult for vanilla RNNs.'),
    q(33, 'If context missing:', ['Better output', 'Wrong prediction', 'Faster model', 'Less loss'], 'Wrong prediction', 'Missing context often leads to poor sequence predictions.'),
    q(34, 'If hidden state lost:', ['Better prediction', 'Poor prediction', 'Faster training', 'Less loss'], 'Poor prediction', 'Losing memory degrades sequence understanding.'),
    q(35, 'Predict next word requires:', ['CNN', 'RNN', 'MLP', 'PCA'], 'RNN', 'Next-word prediction is a recurrent sequence modeling task.'),
    q(36, 'If vanishing gradient occurs:', ['Faster learning', 'No learning', 'Stable learning', 'Better output'], 'No learning', 'When gradients vanish, earlier layers/time steps learn very little.'),
    q(37, 'If exploding gradient occurs:', ['Stable model', 'Unstable model', 'Better learning', 'No effect'], 'Unstable model', 'Exploding gradients cause unstable parameter updates.'),
    q(38, 'If training slow:', ['Reduce sequence length', 'Increase layers', 'Increase data', 'None'], 'Reduce sequence length', 'Shorter sequences can reduce training time.'),
    q(39, 'If model forgets earlier words:', ['Use CNN', 'Use LSTM', 'Remove layers', 'Increase bias'], 'Use LSTM', 'LSTM helps preserve long-term dependencies.'),
    q(40, 'Time-series prediction uses:', ['CNN', 'RNN', 'MLP', 'PCA'], 'RNN', 'Time-series data is sequential and suited to RNNs.'),
    q(41, 'RNN is mathematically:', ['Static mapping', 'Recursive function', 'Linear model', 'Random'], 'Recursive function', 'RNN state transitions are recursive over time.'),
    q(42, 'Weight sharing helps:', ['Increase parameters', 'Reduce parameters', 'Increase loss', 'Store data'], 'Reduce parameters', 'Reusing weights at each step reduces model size.'),
    q(43, 'Hidden state depends on:', ['Input only', 'Previous state only', 'Both', 'None'], 'Both', 'State depends on current input and prior hidden state.'),
    q(44, 'RNN is best for:', ['Spatial patterns', 'Temporal patterns', 'Static patterns', 'Random patterns'], 'Temporal patterns', 'RNNs are designed for temporal dependencies.'),
    q(45, 'Sequence length affects:', ['Output', 'Learning ability', 'Loss', 'Input'], 'Learning ability', 'Longer sequences can make dependency learning harder.'),
    q(46, 'LSTM uses:', ['Filters', 'Gates', 'Pooling', 'Kernels'], 'Gates', 'LSTM uses input, forget, and output gates.'),
    q(47, 'GRU simplifies:', ['CNN', 'LSTM', 'MLP', 'PCA'], 'LSTM', 'GRU is a simplified gated alternative to LSTM.'),
    q(48, 'RNN limitation solved by:', ['CNN', 'LSTM/GRU', 'PCA', 'KNN'], 'LSTM/GRU', 'Gated RNN variants address long-memory issues.'),
    q(49, 'RNN is replaced by:', ['CNN', 'Transformers', 'PCA', 'KNN'], 'Transformers', 'Transformers now dominate many sequence tasks.'),
    q(50, 'RNN strength is:', ['Speed', 'Memory', 'Visualization', 'Storage'], 'Memory', 'RNN strength is modeling contextual memory over sequences.'),
  ],
  'Hopfield Network': [
    q(1, 'What is a Hopfield Network?', ['Feedforward network', 'Recurrent neural network', 'CNN', 'Transformer'], 'Recurrent neural network', 'A Hopfield network is a recurrent neural network with feedback connections.'),
    q(2, 'Hopfield Network is mainly used for:', ['Classification', 'Pattern storage and retrieval', 'Image processing', 'Sorting'], 'Pattern storage and retrieval', 'Its core use is associative memory for stored patterns.'),
    q(3, 'Hopfield Network is:', ['Directed graph', 'Undirected graph', 'Sequential model', 'Tree structure'], 'Undirected graph', 'Connections are symmetric, making it effectively undirected.'),
    q(4, 'Connections in Hopfield network are:', ['One-way', 'Two-way (symmetric)', 'Random', 'None'], 'Two-way (symmetric)', 'Hopfield weights satisfy symmetry for stable convergence behavior.'),
    q(5, 'Hopfield network uses:', ['Hidden layers', 'Single layer of neurons', 'Multiple layers', 'No layers'], 'Single layer of neurons', 'Classic Hopfield networks are single-layer recurrent systems.'),
    q(6, 'Each neuron is connected to:', ['Some neurons', 'All other neurons', 'No neurons', 'Input only'], 'All other neurons', 'The network is fully interconnected except self-connections.'),
    q(7, 'Self-connections in Hopfield network are:', ['Allowed', 'Not allowed', 'Optional', 'Required'], 'Not allowed', 'Diagonal terms are typically zero, so neurons do not connect to themselves.'),
    q(8, 'Output of Hopfield neuron is typically:', ['Continuous', 'Binary (-1, +1)', 'Probability', 'Random'], 'Binary (-1, +1)', 'Discrete Hopfield neurons usually use bipolar states.'),
    q(9, 'Hopfield network stores:', ['Features', 'Patterns', 'Loss', 'Gradients'], 'Patterns', 'Memories are encoded as stable attractor patterns.'),
    q(10, 'Hopfield networks are also called:', ['Memory networks', 'CNN', 'RNN', 'GAN'], 'Memory networks', 'They are a form of associative memory networks.'),
    q(11, 'Network converges to:', ['Random state', 'Stable state', 'Input', 'Output layer'], 'Stable state', 'Iterative updates converge to a stable attractor state.'),
    q(12, 'Stable state represents:', ['Noise', 'Stored pattern', 'Gradient', 'Input'], 'Stored pattern', 'A stable minimum often corresponds to a memorized pattern.'),
    q(13, 'Hopfield network is inspired by:', ['CPU', 'Brain memory', 'GPU', 'Database'], 'Brain memory', 'It is inspired by associative memory behavior in biological systems.'),
    q(14, 'Hopfield network updates neurons:', ['Simultaneously', 'One at a time', 'Randomly', 'None'], 'One at a time', 'Asynchronous updates are commonly used for guaranteed energy decrease.'),
    q(15, 'Hopfield network works best for:', ['Large datasets', 'Small pattern sets', 'Sequential data', 'Images'], 'Small pattern sets', 'Capacity is limited, so it works best with modest memory counts.'),
    q(16, 'Hopfield network minimizes:', ['Loss', 'Energy function', 'Gradient', 'Input'], 'Energy function', 'Dynamics are defined to reduce an energy function.'),
    q(17, 'Energy function represents:', ['Accuracy', 'Stability of network', 'Input', 'Output'], 'Stability of network', 'Lower energy corresponds to more stable network configurations.'),
    q(18, 'Lower energy means:', ['Unstable', 'Stable', 'Random', 'High loss'], 'Stable', 'Energy descent leads to stable attractor states.'),
    q(19, 'Network evolves toward:', ['Higher energy', 'Lower energy', 'Random energy', 'Zero energy'], 'Lower energy', 'Update rules push states toward lower-energy minima.'),
    q(20, 'Weight matrix in Hopfield network is:', ['Asymmetric', 'Symmetric', 'Random', 'Sparse'], 'Symmetric', 'Symmetric weights are a defining condition of classic Hopfield networks.'),
    q(21, 'Why symmetry is important?', ['Faster training', 'Convergence guarantee', 'Reduce data', 'Normalize input'], 'Convergence guarantee', 'Symmetry enables monotonic energy descent and convergence.'),
    q(22, 'Hopfield network is:', ['Supervised', 'Unsupervised', 'Semi-supervised', 'Reinforcement'], 'Unsupervised', 'Pattern storage follows unsupervised associative learning.'),
    q(23, 'Patterns stored are:', ['Independent', 'Distributed', 'Random', 'Sequential'], 'Distributed', 'Information is distributed across many weights.'),
    q(24, 'Network retrieves pattern using:', ['Input only', 'Partial/noisy input', 'Loss', 'Gradient'], 'Partial/noisy input', 'It performs pattern completion from incomplete or noisy cues.'),
    q(25, 'Hopfield network behaves like:', ['Classifier', 'Associative memory', 'Optimizer', 'Sorter'], 'Associative memory', 'It maps corrupted inputs to nearest stored memories.'),
    q(26, 'If noisy input given:', ['Random output', 'Correct pattern', 'Loss increases', 'No output'], 'Correct pattern', 'Within capacity and noise limits, it recalls the original memory.'),
    q(27, 'Storage capacity is:', ['Unlimited', 'Limited', 'Infinite', 'None'], 'Limited', 'Classical Hopfield capacity is finite and scales with neuron count.'),
    q(28, 'Too many patterns cause:', ['Better learning', 'Memory confusion', 'Faster training', 'Stability'], 'Memory confusion', 'Overloading memory leads to recall errors and spurious states.'),
    q(29, 'Hopfield network uses:', ['Backpropagation', 'Hebbian learning', 'Gradient descent', 'Reinforcement'], 'Hebbian learning', 'Weights are often set using Hebbian-style pattern correlation.'),
    q(30, 'Hebbian rule means:', ['Random update', 'Neurons that fire together connect', 'Remove weights', 'Normalize data'], 'Neurons that fire together connect', 'Hebbian learning strengthens co-active neuron connections.'),
    q(31, 'If input is partially correct:', ['Output random', 'Retrieves full pattern', 'Loss increases', 'No change'], 'Retrieves full pattern', 'Associative recall completes partial cues into full memories.'),
    q(32, 'If too many patterns stored:', ['Perfect recall', 'Errors increase', 'Faster learning', 'Stable output'], 'Errors increase', 'Capacity overload increases interference and wrong recalls.'),
    q(33, 'If weights not symmetric:', ['Stable', 'Unstable', 'Faster', 'Accurate'], 'Unstable', 'Without symmetry, energy descent guarantees can break.'),
    q(34, 'If energy increases:', ['Stable', 'Unstable', 'Correct output', 'No change'], 'Unstable', 'Rising energy indicates movement away from stable attractors.'),
    q(35, 'If network converges:', ['Random output', 'Stable pattern', 'Loss', 'Gradient'], 'Stable pattern', 'Convergence means it has settled into a stable memory state.'),
    q(36, 'If noisy pattern input:', ['Correct recall', 'Random output', 'No output', 'Loss increases'], 'Correct recall', 'Robust associative memory can recover original patterns from noise.'),
    q(37, 'Hopfield fails when:', ['Few patterns', 'Too many patterns', 'Small data', 'Low noise'], 'Too many patterns', 'Exceeding capacity produces unreliable recall.'),
    q(38, 'If neuron updates wrong:', ['Better output', 'Wrong pattern', 'Stable output', 'Faster training'], 'Wrong pattern', 'Incorrect updates can drive the state to wrong attractors.'),
    q(39, 'If network stuck in wrong state:', ['Correct recall', 'Local minima', 'Global minimum', 'Perfect output'], 'Local minima', 'Spurious local minima can trap recall in incorrect states.'),
    q(40, 'Energy minimization ensures:', ['Random output', 'Stable recall', 'Faster training', 'No output'], 'Stable recall', 'Minimizing energy supports stable memory retrieval.'),
    q(41, 'Hopfield network is:', ['Feedforward', 'Recurrent', 'Sequential', 'Linear'], 'Recurrent', 'It uses recurrent feedback connections among neurons.'),
    q(42, 'Memory retrieval depends on:', ['Input similarity', 'Loss', 'Gradient', 'Data size'], 'Input similarity', 'Closer noisy inputs are more likely to converge to the correct memory.'),
    q(43, 'Capacity roughly equals:', ['N', 'N/2', '0.15N', '2N'], '0.15N', 'A common approximation for classical Hopfield capacity is about 0.15N patterns.'),
    q(44, 'Hopfield network converges to:', ['Maximum energy', 'Minimum energy', 'Random', 'Zero'], 'Minimum energy', 'Dynamics converge to local minima of the energy landscape.'),
    q(45, 'Symmetric weights ensure:', ['Fast learning', 'Convergence', 'Accuracy', 'Speed'], 'Convergence', 'Symmetric weights are key to guaranteed convergence behavior.'),
    q(46, 'Hopfield network stores patterns in:', ['Layers', 'Weights', 'Inputs', 'Outputs'], 'Weights', 'Memories are encoded in the synaptic weight matrix.'),
    q(47, 'Local minima cause:', ['Correct recall', 'Incorrect recall', 'Faster training', 'Stable output'], 'Incorrect recall', 'Spurious minima can produce wrong memory retrieval.'),
    q(48, 'Hopfield networks are limited by:', ['Speed', 'Capacity', 'Data', 'Loss'], 'Capacity', 'Finite capacity limits how many patterns can be stored reliably.'),
    q(49, 'Hopfield network is used in:', ['Image classification', 'Pattern completion', 'Regression', 'Sorting'], 'Pattern completion', 'Its classic application is associative pattern completion.'),
    q(50, 'Main strength of Hopfield network:', ['Speed', 'Memory recall', 'Visualization', 'Training'], 'Memory recall', 'The key strength is robust associative memory recall.'),
  ],
}

export function getQuizQuestions(moduleName) {
  const questions = QUIZ_BANK[moduleName] || []
  if (questions.length <= QUIZ_SELECTION_COUNT) {
    return questions.slice()
  }

  const shuffled = questions.slice()
  for (let i = shuffled.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }

  return shuffled.slice(0, QUIZ_SELECTION_COUNT)
}
